<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StudentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'nis' => '',
                'user_id' => '12',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '13',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '14',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '15',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '16',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '17',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '18',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '19',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '20',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '21',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '22',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '23',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '24',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '25',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '26',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '27',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '28',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '29',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '30',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '31',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '32',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '33',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '34',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '35',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '36',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '37',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '38',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '39',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '40',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '41',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '42',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '43',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '44',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '45',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '46',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '47',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '48',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '49',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '50',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '51',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '52',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '53',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '54',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '55',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '56',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '57',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '58',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '59',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '60',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '61',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '62',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '63',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '64',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '65',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '66',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '67',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '68',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '69',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '70',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '71',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '72',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '73',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '74',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '75',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '76',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '77',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '78',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '79',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '80',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '81',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '82',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '83',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '84',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '85',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '86',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '87',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '88',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '89',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '90',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '91',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '92',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '93',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '94',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '95',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '96',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '97',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '98',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '99',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '100',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '101',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '102',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '103',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '104',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '105',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '106',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '107',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '108',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '109',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '110',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '111',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '112',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '113',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '24',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '25',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '26',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '27',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '28',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '29',
                'nisn' => '',
                'fullname' => '',
                'gender' => '',
                'level' => '',
                'address' => '',
                'date_of_birth' => '',
                'status' =>  1,
            ],

        ];

        foreach ($students as $key => $student) {
            Student::create($students);
        }
    }
}
