<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StudentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'nis' => '00012324',
                'user_id' => '12',
                'nisn' => '3163973753',
                'fullname' => 'ABIZAR KHAIRUL ANAM',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00022324',
                'user_id' => '13',
                'nisn' => '316502830',
                'fullname' => 'ACHSAN HUSAIN',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00032324',
                'user_id' => '14',
                'nisn' => '3170651274',
                'fullname' => 'ADIFA AZALINA PUTRI',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00042324',
                'user_id' => '15',
                'nisn' => '3172982977',
                'fullname' => 'AFRA NAYLA',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00052324',
                'user_id' => '16',
                'nisn' => '3168456466',
                'fullname' => 'AHMAD FAUZAN',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00062324',
                'user_id' => '17',
                'nisn' => '0164212562',
                'fullname' => 'AHMAD FHATIR',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00062324',
                'user_id' => '18',
                'nisn' => '3167635989',
                'fullname' => 'AHMAD RIO SANJAYA TASMIN',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00062324',
                'user_id' => '19',
                'nisn' => '3177043943',
                'fullname' => 'AINUR SHANUM FELYSIA',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00082324',
                'user_id' => '20',
                'nisn' => '3161424049',
                'fullname' => 'AISYA FARHANA',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00092324',
                'user_id' => '21',
                'nisn' => '3171767300',
                'fullname' => 'AISYAH SALSABILA',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00102324',
                'user_id' => '22',
                'nisn' => '3179031423',
                'fullname' => 'ALIQA NAU URANA',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00122324',
                'user_id' => '23',
                'nisn' => '3176243512',
                'fullname' => 'ARSYILA FARISA',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00132324',
                'user_id' => '24',
                'nisn' => '3164967230',
                'fullname' => 'Hafiza Khaira Lubna',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00142324',
                'user_id' => '25',
                'nisn' => '0165733227',
                'fullname' => 'HAFZAH LATIFAH. H',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00152324',
                'user_id' => '26',
                'nisn' => '0165320596',
                'fullname' => 'IPA SASKIA RAHMA',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00162324',
                'user_id' => '27',
                'nisn' => '3175677440',
                'fullname' => 'M. HUSAIN AZKA.B',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00232324',
                'user_id' => '28',
                'nisn' => '3163706283',
                'fullname' => 'MOH. ZAINI NAPO',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00172324',
                'user_id' => '29',
                'nisn' => '3169477826',
                'fullname' => 'MUH. ALL GIBRAN',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00182324',
                'user_id' => '30',
                'nisn' => '3165876174',
                'fullname' => 'MUH. JIBRIL ALFIAN',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00192324',
                'user_id' => '31',
                'nisn' => '3169822106',
                'fullname' => 'MUH. ROBI',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00202324',
                'user_id' => '32',
                'nisn' => '3178347362',
                'fullname' => 'MUHAMMAD FARID ATALLAH',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00212324',
                'user_id' => '33',
                'nisn' => '3164009404',
                'fullname' => 'MUHAMMAD NAIM',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            // 
            [
                'nis' => '00222324',
                'user_id' => '34',
                'nisn' => '3172866828',
                'fullname' => 'MUHAMMAD SAFAAT',
                'gender' => 1,
                'level' => '',
                'address' => '1',
                'date_of_birth' => '',
                'status' =>  1,
            ],
            [
                'nis' => '00242324',
                'user_id' => '35',
                'nisn' => '3161178833',
                'fullname' => 'NUR AULIAH',
                'gender' => 0,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00252324',
                'user_id' => '36',
                'nisn' => '3177582278',
                'fullname' => 'NUR AULYA',
                'gender' => 1,
                'level' => '1',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            // Kelas 2
            [
                'nis' => '00012223',
                'user_id' => '37',
                'nisn' => '0151844427',
                'fullname' => 'ABD. BASIT USMAN',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00022223',
                'user_id' => '38',
                'nisn' => '3147354665',
                'fullname' => 'AHMAD',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00032223',
                'user_id' => '39',
                'nisn' => '315890150',
                'fullname' => 'AHMAD ABIL AMRI',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00042223',
                'user_id' => '40',
                'nisn' => '3163933622',
                'fullname' => 'AINUN NURAISYAH TASRIK',
                'gender' => 0,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00052223',
                'user_id' => '41',
                'nisn' => '3153666203',
                'fullname' => 'AISYAH NUGRAH',
                'gender' => 0,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00062223',
                'user_id' => '42',
                'nisn' => '3153321849',
                'fullname' => 'AISYAH NURROHMAH',
                'gender' => 0,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00072223',
                'user_id' => '43',
                'nisn' => '3167810254',
                'fullname' => 'AUREL AINUN JARIA',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00082223',
                'user_id' => '44',
                'nisn' => '3152623197',
                'fullname' => 'DZAKY ALMAIR JAMIL YUSRI',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00092223',
                'user_id' => '45',
                'nisn' => '3159210366',
                'fullname' => 'HANIF ABBAD',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00122223',
                'user_id' => '46',
                'nisn' => '0159736305',
                'fullname' => 'M. ABID MUBARAK',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00102223',
                'user_id' => '47',
                'nisn' => '3150154412',
                'fullname' => 'MASITA',
                'gender' => 0,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00112223',
                'user_id' => '48',
                'nisn' => '3165740733',
                'fullname' => 'MOH. ARYENDRA PUTRA TINOMBALA',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00132223',
                'user_id' => '49',
                'nisn' => '3153324580',
                'fullname' => 'MUH. ABISAR',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00142223',
                'user_id' => '50',
                'nisn' => '3159862455',
                'fullname' => 'MUH. ABQA ALAN',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00152223',
                'user_id' => '51',
                'nisn' => '3166760496',
                'fullname' => 'MUH. APRIAKZA MAULANA',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00182223',
                'user_id' => '52',
                'nisn' => '3155181317',
                'fullname' => 'MUH. FIRMANSYAH',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00192223',
                'user_id' => '53',
                'nisn' => '0138813363',
                'fullname' => 'MUH. KHAIRUL',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00202223',
                'user_id' => '54',
                'nisn' => '3168204514',
                'fullname' => 'MUH. ZULFADHLI',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00162223',
                'user_id' => '55',
                'nisn' => '3153699984',
                'fullname' => 'MUHAMMAD AIDHIL AL KAHFI',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00172223',
                'user_id' => '56',
                'nisn' => '0156536569',
                'fullname' => 'MUHAMMAD FILI MUTTAQIN',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00212223',
                'user_id' => '57',
                'nisn' => '3155154128',
                'fullname' => 'NAJWA KHAIRA WILDA',
                'gender' => 1,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => 'NAYZILA AZZAHRA',
                'user_id' => '58',
                'nisn' => '0135269773',
                'fullname' => '00222223',
                'gender' => 0,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00232223',
                'user_id' => '59',
                'nisn' => '3163943803',
                'fullname' => 'SITI FATIMAH',
                'gender' => 0,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00222122',
                'user_id' => '60',
                'nisn' => '0151260983',
                'fullname' => 'TITA NURHALIMA',
                'gender' => 0,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00242223',
                'user_id' => '61',
                'nisn' => '3166155086',
                'fullname' => 'ZYINDI AMELIA. A',
                'gender' => 0,
                'level' => '2',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            // Kelas 3
            [
                'nis' => '00022122',
                'user_id' => '62',
                'nisn' => '0149582474',
                'fullname' => 'AFWANY',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00012122',
                'user_id' => '63',
                'nisn' => '3141162702',
                'fullname' => 'AHMAD FAI MUHSIN',
                'gender' => 1,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00032122',
                'user_id' => '64',
                'nisn' => '3141162702',
                'fullname' => 'AHMAD FARIS',
                'gender' => 1,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00042122',
                'user_id' => '65',
                'nisn' => '3140986872',
                'fullname' => 'AINUN HABIBI',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00052122',
                'user_id' => '66',
                'nisn' => '3144352766',
                'fullname' => 'ALFAR TSABIT AL-QEIS',
                'gender' => 1,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00062122',
                'user_id' => '67',
                'nisn' => '3149789986',
                'fullname' => 'ARIFATUL ROHMAH',
                'gender' => 1,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00072122',
                'user_id' => '68',
                'nisn' => '0146430320',
                'fullname' => 'FADHLIAH',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00092122',
                'user_id' => '69',
                'nisn' => '0153463531',
                'fullname' => 'HAJRA',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00102122',
                'user_id' => '70',
                'nisn' => '0159737180',
                'fullname' => 'HUMAIRAH',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00122122',
                'user_id' => '71',
                'nisn' => '0148526206',
                'fullname' => 'MUH. WAVIQ',
                'gender' => 1,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00132122',
                'user_id' => '72',
                'nisn' => '0157744771',
                'fullname' => 'MUH.ZAKI ARDANI',
                'gender' => 1,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '23240026',
                'user_id' => '73',
                'nisn' => '3149454805',
                'fullname' => 'MUHAMMAD ABILAL',
                'gender' => 1,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '200112122',
                'user_id' => '74',
                'nisn' => '3157495418',
                'fullname' => 'MUHAMMAD FAHRIL',
                'gender' => 1,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '',
                'user_id' => '75',
                'nisn' => '0148448688',
                'fullname' => 'NUR ADILA PUTRI',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00172122',
                'user_id' => '76',
                'nisn' => '0142762170',
                'fullname' => 'NUR HAZANA',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00162122',
                'user_id' => '77',
                'nisn' => '0143801547',
                'fullname' => 'NUR HAZINA AMILA',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00142122',
                'user_id' => '78',
                'nisn' => '0149244380',
                'fullname' => 'NURAMYLA ZAHRA',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00182122',
                'user_id' => '79',
                'nisn' => '0151443779 ',
                'fullname' => 'PUTRI ANRIANI TASRIF',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00192122',
                'user_id' => '80',
                'nisn' => '0143451367',
                'fullname' => 'PUTRI NOER NAJWA',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00202122',
                'user_id' => '81',
                'nisn' => '0149318005',
                'fullname' => 'SALSA BYLAH',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00212122',
                'user_id' => '82',
                'nisn' => '0143727866',
                'fullname' => 'SHAFINA ZAHIRA TAFSIR',
                'gender' => 0,
                'level' => '3',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            // Kelas 4
            [
                'nis' => '00012021',
                'user_id' => '83',
                'nisn' => '313324112',
                'fullname' => 'AHMAD AL GIBRAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00022021',
                'user_id' => '84',
                'nisn' => '0132801249',
                'fullname' => 'AYYUB ARDIANSYAPUTRA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00152021',
                'user_id' => '85',
                'nisn' => '0149713813',
                'fullname' => 'CAHAYA MUNIFA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00032021',
                'user_id' => '86',
                'nisn' => '0137492622s',
                'fullname' => 'FAREL ALFARIZI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00042021',
                'user_id' => '87',
                'nisn' => '0146552933',
                'fullname' => 'FATIHA MAISYARAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00052021',
                'user_id' => '88',
                'nisn' => '0132083373',
                'fullname' => 'FIKRY',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '22230025',
                'user_id' => '89',
                'nisn' => '0149603274',
                'fullname' => 'IFFA UFAIRA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00062021',
                'user_id' => '90',
                'nisn' => '3134778103',
                'fullname' => 'M. GHAZALI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00072021',
                'user_id' => '91',
                'nisn' => '0147268471',
                'fullname' => 'MUFIDA SALSABILA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00082021',
                'user_id' => '92',
                'nisn' => '0133797776',
                'fullname' => 'MUH.AINUR ROYAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '21220025',
                'user_id' => '93',
                'nisn' => '0149032510',
                'fullname' => 'MUHAMMAD KHIAR ALTAAF MUFASA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00092021',
                'user_id' => '94',
                'nisn' => '3121228412',
                'fullname' => 'MUHAMMAD SIKRA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00102021',
                'user_id' => '95',
                'nisn' => '0133307059',
                'fullname' => 'MUHAMMAD SYIAR',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '22230026',
                'user_id' => '96',
                'nisn' => '0134040890',
                'fullname' => 'NAUFAL ALGIFHARI YUSRI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '21220026',
                'user_id' => '97',
                'nisn' => '',
                'fullname' => 'Nur Fitrih',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00122021',
                'user_id' => '98',
                'nisn' => '3138260942',
                'fullname' => 'RAIDA FAKHIRA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00132021',
                'user_id' => '99',
                'nisn' => '0143050033',
                'fullname' => 'RESKI AMELIA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00142021',
                'user_id' => '100',
                'nisn' => '',
                'fullname' => 'USWATUL ILMI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '21220029',
                'user_id' => '101',
                'nisn' => '',
                'fullname' => 'ABDUL AHMAD JAYAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00021920',
                'user_id' => '102',
                'nisn' => '',
                'fullname' => 'AHMAD FADLAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '23240027',
                'user_id' => '103',
                'nisn' => '',
                'fullname' => 'AHMAD FUDAIL',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00031920',
                'user_id' => '104',
                'nisn' => '',
                'fullname' => 'AHMAD MIZWAR',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00041920',
                'user_id' => '105',
                'nisn' => '',
                'fullname' => 'ALEA ZANAYA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00051920',
                'user_id' => '106',
                'nisn' => '',
                'fullname' => 'ALIN SYAPUTRA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00061920',
                'user_id' => '107',
                'nisn' => '',
                'fullname' => 'ANITA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00071920',
                'user_id' => '108',
                'nisn' => '',
                'fullname' => 'AQILAH QARIMAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '22230027',
                'user_id' => '109',
                'nisn' => '',
                'fullname' => 'Atiqa Naila',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00081920',
                'user_id' => '110',
                'nisn' => '',
                'fullname' => 'AYU WARDAH SOFIA ABUBAKAR',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00091920',
                'user_id' => '111',
                'nisn' => '',
                'fullname' => 'CAHAYA FADILAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '20210017',
                'user_id' => '112',
                'nisn' => '',
                'fullname' => 'Dwi Maulidia Rabbani',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00101920',
                'user_id' => '113',
                'nisn' => '',
                'fullname' => 'FADILA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00111920',
                'user_id' => '114',
                'nisn' => '',
                'fullname' => 'LUTFI ZAHRAWI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00121920',
                'user_id' => '115',
                'nisn' => '',
                'fullname' => 'M.ALFAN NURUL IHCSAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00131920',
                'user_id' => '116',
                'nisn' => '',
                'fullname' => 'M.RASMAN AL RISQI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00141920',
                'user_id' => '117',
                'nisn' => '',
                'fullname' => 'MOH.TAHIR NAPO',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00161920',
                'user_id' => '118',
                'nisn' => '',
                'fullname' => 'MUH ADAM',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00181920',
                'user_id' => '119',
                'nisn' => '',
                'fullname' => 'MUH. FADHLIN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00171920',
                'user_id' => '120',
                'nisn' => '',
                'fullname' => 'MUH.AHLIF',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00151920',
                'user_id' => '121',
                'nisn' => '',
                'fullname' => 'MUHAMMAD ABRAHAM AL BIRRU',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00191920',
                'user_id' => '122',
                'nisn' => '',
                'fullname' => 'MUHAMMAD ALIM',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '21220024',
                'user_id' => '123',
                'nisn' => '',
                'fullname' => 'MUHAMMAD ATHARIZZ CALIEF',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00201920',
                'user_id' => '124',
                'nisn' => '',
                'fullname' => 'MUHAMMAD FADHIL',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00211920',
                'user_id' => '125',
                'nisn' => '',
                'fullname' => 'MUHAMMAD HIKMAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00221920',
                'user_id' => '126',
                'nisn' => '',
                'fullname' => 'MUHAMMAD SHAFWAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00231920',
                'user_id' => '127',
                'nisn' => '',
                'fullname' => 'MUNAWARA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00241920',
                'user_id' => '128',
                'nisn' => '',
                'fullname' => 'NUR ANNISIYA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00251920',
                'user_id' => '129',
                'nisn' => '',
                'fullname' => 'NUR HAURA NATIFAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00261920',
                'user_id' => '130',
                'nisn' => '',
                'fullname' => 'NUR SISKA AULIA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00271920',
                'user_id' => '131',
                'nisn' => '',
                'fullname' => 'NURUL AZZAHRA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00281920',
                'user_id' => '132',
                'nisn' => '',
                'fullname' => 'QEYLA PUTRI RAMADHANY',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00291920',
                'user_id' => '133',
                'nisn' => '',
                'fullname' => 'Risky Aditia',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00301920',
                'user_id' => '134',
                'nisn' => '',
                'fullname' => 'SALSABILAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00311920',
                'user_id' => '135',
                'nisn' => '',
                'fullname' => 'ZAHRA JANUARI LESTARI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00321920',
                'user_id' => '136',
                'nisn' => '',
                'fullname' => 'ZAKI HUSAIN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00011819',
                'user_id' => '137',
                'nisn' => '',
                'fullname' => 'ABD.RAHMAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => ' 00021819',
                'user_id' => '138',
                'nisn' => '',
                'fullname' => 'AHMAD FAHRIZIQ',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00031819',
                'user_id' => '139',
                'nisn' => '',
                'fullname' => 'AHMAD FAUZAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00041819',
                'user_id' => '140',
                'nisn' => '',
                'fullname' => 'AKSAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00051819',
                'user_id' => '141',
                'nisn' => '',
                'fullname' => 'AMALIA SALSA BILA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00061819',
                'user_id' => '142',
                'nisn' => '',
                'fullname' => 'AMISYA PUTRI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00071819',
                'user_id' => '143',
                'nisn' => '',
                'fullname' => 'ARIF SAPUTRA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00081819',
                'user_id' => '144',
                'nisn' => '',
                'fullname' => 'CITRA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00091819',
                'user_id' => '145',
                'nisn' => '',
                'fullname' => 'FAHRUDDIN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00101819',
                'user_id' => '146',
                'nisn' => '',
                'fullname' => 'FEBRIANTI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00111819',
                'user_id' => '147',
                'nisn' => '',
                'fullname' => 'FITRIANI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00121819',
                'user_id' => '148',
                'nisn' => '',
                'fullname' => 'LATHIFAH KAMILAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00151718',
                'user_id' => '149',
                'nisn' => '',
                'fullname' => 'M. MAULANA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00131819',
                'user_id' => '150',
                'nisn' => '',
                'fullname' => 'M.UBAI ABDILLAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00141819',
                'user_id' => '151',
                'nisn' => '',
                'fullname' => 'MARWAH FADILA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00151819',
                'user_id' => '152',
                'nisn' => '',
                'fullname' => 'MELISA ZALZABILA WAHAB',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00161819',
                'user_id' => '153',
                'nisn' => '',
                'fullname' => 'MILAD SYARWAN NUR',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '21220028',
                'user_id' => '154',
                'nisn' => '',
                'fullname' => 'Muh. Nizam Habibi',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00211819',
                'user_id' => '155',
                'nisn' => '',
                'fullname' => 'MUH. QHALBUN SALIM',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00221819',
                'user_id' => '156',
                'nisn' => '',
                'fullname' => 'MUH. REZA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00171819',
                'user_id' => '157',
                'nisn' => '',
                'fullname' => 'MUH.ALWI AKHSAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00181819',
                'user_id' => '158',
                'nisn' => '',
                'fullname' => 'MUH.ARJIDAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00191819',
                'user_id' => '159',
                'nisn' => '',
                'fullname' => 'MUH.AYMAN AMIRUL',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00201819',
                'user_id' => '160',
                'nisn' => '',
                'fullname' => 'MUH.NAESAR',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00231819',
                'user_id' => '161',
                'nisn' => '',
                'fullname' => 'MUHAMMAD ALFIAN',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00101718',
                'user_id' => '162',
                'nisn' => '',
                'fullname' => 'MUHAMMAD ARIF REZKY',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '21220030',
                'user_id' => '163',
                'nisn' => '',
                'fullname' => 'Muhammad Yusuf Murdiansyah',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00241819',
                'user_id' => '164',
                'nisn' => '',
                'fullname' => 'MULIAWAN RAMADANI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00251819',
                'user_id' => '165',
                'nisn' => '',
                'fullname' => 'MURSALIM',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00261819',
                'user_id' => '166',
                'nisn' => '',
                'fullname' => 'MURSALIM',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00271819',
                'user_id' => '167',
                'nisn' => '',
                'fullname' => 'NAPIA NURHIDAYAH SAHRUL',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00281819',
                'user_id' => '168',
                'nisn' => '',
                'fullname' => 'NUR LATHIFA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00291819',
                'user_id' => '169',
                'nisn' => '',
                'fullname' => 'NURMADANI',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00301819',
                'user_id' => '170',
                'nisn' => '',
                'fullname' => 'NURUL FAUZIAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00311819',
                'user_id' => '171',
                'nisn' => '',
                'fullname' => 'RAHMA FAUZIAH',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00321819',
                'user_id' => '172',
                'nisn' => '',
                'fullname' => 'RESKI ZALSABILA',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => 'ZAHRA MUTIARA',
                'user_id' => '173',
                'nisn' => '',
                'fullname' => '00331819',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],
            [
                'nis' => '00341819',
                'user_id' => '174',
                'nisn' => '',
                'fullname' => 'ZYIFA CAHYA.A',
                'gender' => '',
                'level' => '',
                'address' => 'Kec. Limboro',
                'date_of_birth' => '2023-12-30',
                'status' =>  1,
            ],

        ];

        foreach ($students as $key => $student) {
            Student::create($students);
        }
    }
}
